/**
 * A dark theme set by inverting the colors found in the default set of variables
 * @type {Object}
 */
export const varsDark = Object.freeze({
    "--theme-color-bg": "var(--theme-color-0)",
    "--theme-color-fg": "var(--theme-color-9)",
    "--theme-color-link": "var(--theme-color-accent-info-3)",
    "--theme-color-0": "#000000",
    "--theme-color-1": "#2D2D2D",
    "--theme-color-2": "#565656",
    "--theme-color-3": "#656565",
    "--theme-color-4": "#8A8A8A",
    "--theme-color-5": "#ADADAD",
    "--theme-color-6": "#C5C5C5",
    "--theme-color-7": "#DCDCDC",
    "--theme-color-8": "#ECECEC",
    "--theme-color-9": "#FFFFFF",
    "--theme-color-accent-info-0": "#00659c",
    "--theme-color-accent-info-1": "#0088ce",
    "--theme-color-accent-info-2": "#39a5dc",
    "--theme-color-accent-info-3": "#bee1f4",
    "--theme-color-accent-info-4": "#def3ff",
    "--theme-color-accent-success-0": "#2d7623",
    "--theme-color-accent-success-1": "#3f9c35",
    "--theme-color-accent-success-2": "#6ec664",
    "--theme-color-accent-success-3": "#9ecf99",
    "--theme-color-accent-success-4": "#cfe7cd",
    "--theme-color-accent-alert-0": "#dda600",
    "--theme-color-accent-alert-1": "#f9c62c",
    "--theme-color-accent-alert-2": "#f9d463",
    "--theme-color-accent-alert-3": "#f9e4a4",
    "--theme-color-accent-alert-4": "#fcf6e3",
    "--theme-color-accent-warning-0": "#f4581f",
    "--theme-color-accent-warning-1": "#ff8330",
    "--theme-color-accent-warning-2": "#ffa86b",
    "--theme-color-accent-warning-3": "#ffc57a",
    "--theme-color-accent-warning-4": "#ffe2af",
    "--theme-color-accent-error-0": "#BD1818",
    "--theme-color-accent-error-1": "#FF171A",
    "--theme-color-accent-error-2": "#FF4B4B",
    "--theme-color-accent-error-3": "#FF7A7A",
    "--theme-color-accent-error-4": "#F9CACA",
    "--theme-color-msg-success-bg": "var(--theme-color-accent-success-0)",
    "--theme-color-msg-success-fg": "var(--theme-color-accent-success-4)",
    "--theme-color-msg-alert-bg": "var(--theme-color-accent-alert-0)",
    "--theme-color-msg-alert-fg": "var(--theme-color-accent-alert-4)",
    "--theme-color-msg-warning-bg": "var(--theme-color-accent-warning-0)",
    "--theme-color-msg-warning-fg": "var(--theme-color-accent-warning-4)",
    "--theme-color-msg-info-bg": "var(--theme-color-accent-info-0)",
    "--theme-color-msg-info-fg": "var(--theme-color-accent-info-4)",
    "--theme-color-msg-error-bg": "var(--theme-color-accent-error-0)",
    "--theme-color-msg-error-fg": "var(--theme-color-accent-error-4)",
    "--theme-font-size-xxl": "28px",
    "--theme-font-size-xl": "21px",
    "--theme-font-size-l": "17px",
    "--theme-font-size-m": "14px",
    "--theme-font-size-s": "12px",
    "--theme-font-size-xs": "11px",
    "--theme-font-family": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
    "--theme-font-family-monospace": "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
    "--theme-spacing-0": "0",
    "--theme-spacing-1": "0.25rem",
    "--theme-spacing-2": "0.5rem",
    "--theme-spacing-3": "0.75rem",
    "--theme-spacing-4": "1rem",
    "--theme-spacing-5": "1.25rem",
    "--theme-spacing-6": "1.5rem",
    "--theme-spacing-7": "1.75rem",
    "--theme-spacing-8": "2rem",
    "--theme-box-shadow": "0 8px 10px 1px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2)",
    "--theme-box-shadow-n": "0 -8px 10px 1px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2)",
    "--theme-box-shadow-e": "8px 0 10px 1px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2)",
    "--theme-box-shadow-s": "var(--theme-box-shadow)",
    "--theme-box-shadow-w": "-8px 0 10px 1px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2)"
});
